/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;
import static GUIs.FirstPageGUI.bP;


import Helper.DBConnection;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import static GUIs.BankProjectGUI.data;

/**
 *
 * @author TURBOX
 */
public class bakiyeGUI extends javax.swing.JFrame {

    /**
     * Creates new form ödemelerGUI
     */
    public bakiyeGUI() {
       
            initComponents();
            update((String) data[2],(String) data[3]);
            showBakiye((String) data[2], (int) data[5]);
           
            
    }
    private void showBakiye(String tcno,int bakiye){
         try {
                Connection con=conn.connDB();
            
                st=con.createStatement();
                rs=st.executeQuery("SELECT * FROM user  WHERE tcno="+tcno);
            while(rs.next()){
                bakiyeLbl.setText("BANKAMIZDA BULUNAN MEVCUT BAKİYENİZ " +bakiye + "TL");
    }
            } catch (SQLException ex) {
                Logger.getLogger(bakiyeGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        geriParaCekBtn = new javax.swing.JButton();
        geriParaYatBtn = new javax.swing.JButton();
        bakiyeLbl = new javax.swing.JLabel();
        geriYatırBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 500));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/kurtbank.png"))); // NOI18N

        geriParaCekBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        geriParaCekBtn.setText("PARA ÇEK");
        geriParaCekBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriParaCekBtnActionPerformed(evt);
            }
        });

        geriParaYatBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        geriParaYatBtn.setText("PARA YATIR");
        geriParaYatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriParaYatBtnActionPerformed(evt);
            }
        });

        bakiyeLbl.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        bakiyeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        geriYatırBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        geriYatırBtn.setText("<<  GERİ");
        geriYatırBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriYatırBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bakiyeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(geriYatırBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(geriParaCekBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(geriParaYatBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(bakiyeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(geriParaYatBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(geriParaCekBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geriYatırBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

       
    
    private void geriParaCekBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriParaCekBtnActionPerformed
      cekmeGUI cek=new cekmeGUI();
       cek.setVisible(true);
       
        dispose();
    }//GEN-LAST:event_geriParaCekBtnActionPerformed

    private void geriParaYatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriParaYatBtnActionPerformed
        yatırmaGUI yatır=new yatırmaGUI();
       yatır.setVisible(true);
       
        dispose();
    }//GEN-LAST:event_geriParaYatBtnActionPerformed

    private void geriYatırBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriYatırBtnActionPerformed
        FirstPageGUI fpGUI=new FirstPageGUI();
        fpGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_geriYatırBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bakiyeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bakiyeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bakiyeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bakiyeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new bakiyeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bakiyeLbl;
    private javax.swing.JButton geriParaCekBtn;
    private javax.swing.JButton geriParaYatBtn;
    private javax.swing.JButton geriYatırBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
DBConnection conn=new DBConnection();
Statement st=null;
ResultSet rs=null;
PreparedStatement pt=null;

   private void update(String tcno,String sifre) {
          try {
            Connection con=conn.connDB();
            st=con.createStatement();
            String query="SELECT*FROM user WHERE tcno='"+tcno+"'AND sifre='"+sifre+"'";
            //String query="SELECT*FROM user WHERE ";
            rs=st.executeQuery(query);
            while(rs.next()){
                
                data[5]=rs.getInt("bakiye");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(BankProjectGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   public void runUpdate(){
       update((String) data[2],(String) data[3]);
   }
}
    
    



