/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;


import static GUIs.bakiyeGUI.*;
import static GUIs.yatırmaGUI.act;
import Helper.DBConnection;
import bankproject.User;
import bankproject.BankProject;
import bankproject.Costumer;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;

import javax.swing.JOptionPane;
import static GUIs.BankProjectGUI.data;
/**
 *
 * @author TURBOX
 */
public class cekmeGUI extends javax.swing.JFrame {
boolean key=false;
 BankProject bP=new BankProject();
 bakiyeGUI bGUI=new bakiyeGUI();
    /**
     * Creates new form cekmeGUI
     */
    public cekmeGUI() {
    try {
        initComponents();
        Connection con=conn.connDB();
        st=con.createStatement();
        rs=st.executeQuery("SELECT * FROM user");
                while(rs.next()){
                    String bakiye=String.valueOf(data[5]);
                    mevcutCekTxt.setText(bakiye);
                }
    } catch (SQLException ex) {
        Logger.getLogger(cekmeGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
       
        
    }
     public int cekme(int ebakiye,String tcno,int cekilen){
        int ybakiye=0;
        if(ebakiye>0&&ebakiye>=cekilen){
          try {
            
            ybakiye=ebakiye-cekilen;
            
            Connection con=conn.connDB();
            String query="UPDATE user SET bakiye=? WHERE tcno=?";
            //st=con.createStatement();
            pt=con.prepareStatement(query);
            pt.setInt(1, ybakiye);
            pt.setString(2, tcno);
            pt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Para Cekme İşLemi Başarı İle Gerçekleşti");
            key=true;
         
        } catch (SQLException ex) {
            Logger.getLogger(Costumer.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "Bakiyenin Yetersizdir","DİKKAT!",JOptionPane.WARNING_MESSAGE);
        }
           return ybakiye;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cekilecekTutar = new javax.swing.JLabel();
        mevcutBakiyeLbl = new javax.swing.JLabel();
        cekilecekTxt = new javax.swing.JTextField();
        mevcutCekTxt = new javax.swing.JTextField();
        cekBtn = new javax.swing.JButton();
        geriBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 500));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/kurtbank.png"))); // NOI18N

        cekilecekTutar.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        cekilecekTutar.setText("Cekilecek Tutar");

        mevcutBakiyeLbl.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        mevcutBakiyeLbl.setText("Mevcut Bakiyeniz");

        cekilecekTxt.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N

        mevcutCekTxt.setEditable(false);
        mevcutCekTxt.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N

        cekBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        cekBtn.setText("ÇEK");
        cekBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekBtnActionPerformed(evt);
            }
        });

        geriBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        geriBtn.setText("<<  GERİ");
        geriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mevcutBakiyeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mevcutCekTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cekilecekTutar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(geriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cekBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(cekilecekTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mevcutBakiyeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mevcutCekTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cekilecekTutar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cekilecekTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cekBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geriBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cekBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekBtnActionPerformed
       
      if(cekilecekTxt.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Lütfen Çekilecek Tutarı Giriniz!!!","DİKKAT!",JOptionPane.WARNING_MESSAGE);
      }else{
          try{
          Connection con=conn.connDB();
          st=con.createStatement();
          rs=st.executeQuery("SELECT*FROM user");
          while(rs.next()){
          cekme((int) data[5], (String) data[2],Integer.parseInt(cekilecekTxt.getText()));
             bGUI.runUpdate();
              act.AddActivity((String)data[1], (String)data[2],Integer.parseInt(cekilecekTxt.getText()),(int)data[5], "ÇEKİLEN", (String)data[4]);
           mevcutCekTxt.setText(String.valueOf(data[5]));
                  cekilecekTxt.setText(null);
                  
                                 FirstPageGUI fpGUI=new FirstPageGUI();
                                 fpGUI.setVisible(true);
                                dispose();
                  break;
          }
          
          }catch (SQLException ex) {
                  Logger.getLogger(yatırmaGUI.class.getName()).log(Level.SEVERE, null, ex);
              }
            
      
        
         }                     
        
          
       
    }//GEN-LAST:event_cekBtnActionPerformed

    private void geriBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriBtnActionPerformed
       FirstPageGUI fpGUI=new FirstPageGUI();
               fpGUI.setVisible(true);
               dispose();
    }//GEN-LAST:event_geriBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cekmeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cekmeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cekmeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cekmeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cekmeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekBtn;
    private javax.swing.JLabel cekilecekTutar;
    private javax.swing.JTextField cekilecekTxt;
    private javax.swing.JButton geriBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel mevcutBakiyeLbl;
    private javax.swing.JTextField mevcutCekTxt;
    // End of variables declaration//GEN-END:variables
    DBConnection conn=new DBConnection();
    Connection con=conn.connDB();
    Statement st=null;
    ResultSet rs=null;
    PreparedStatement pt=null;

   
    
}
