/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;
import java.sql.*;
import Helper.DBConnection;
import bankproject.BankProject;
import bankproject.Costumer;
import bankproject.User;
import java.util.logging.Level;
import java.util.logging.Logger;
import static GUIs.BankProjectGUI.data;
/**
 *
 * @author TURBOX
 */
public class FirstPageGUI extends javax.swing.JFrame {
  // static Costumer u1=new Costumer();
   static BankProject bP=new BankProject();
    /**
     * Creates new form FirstPageGUI
     */
    public FirstPageGUI() {
         initComponents();
      try {
          
           Connection con=conn.connDB();
           Statement st=con.createStatement();
           ResultSet rs=st.executeQuery("SELECT*FROM user");
           while(rs.next()){
               welcomeLbl2.setText("Hoşgeldiniz Sayın " +data[1]);
           }
       } catch (SQLException ex) {
           Logger.getLogger(FirstPageGUI.class.getName()).log(Level.SEVERE, null, ex);
       }
     
    }
   
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        welcomeLbl2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        yatırmaBtn = new javax.swing.JButton();
        cekmeBtn = new javax.swing.JButton();
        bakiyeBtn = new javax.swing.JButton();
        cıkısYapBtn = new javax.swing.JButton();
        sifreBtn = new javax.swing.JButton();
        hesapDokumBtn = new javax.swing.JButton();
        transferBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 500));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/kurtbank.png"))); // NOI18N

        welcomeLbl2.setFont(new java.awt.Font("MS UI Gothic", 1, 14)); // NOI18N
        welcomeLbl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        yatırmaBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        yatırmaBtn.setText("PARA ÇEKME");
        yatırmaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yatırmaBtnActionPerformed(evt);
            }
        });

        cekmeBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        cekmeBtn.setText("PARA YATIRMA");
        cekmeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekmeBtnActionPerformed(evt);
            }
        });

        bakiyeBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        bakiyeBtn.setText("BAKİYE SORGULAMA");
        bakiyeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bakiyeBtnActionPerformed(evt);
            }
        });

        cıkısYapBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        cıkısYapBtn.setText("ÇIKIŞ YAP");
        cıkısYapBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cıkısYapBtnActionPerformed(evt);
            }
        });

        sifreBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        sifreBtn.setText("ŞİFRE İSLEMLERİ");
        sifreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sifreBtnActionPerformed(evt);
            }
        });

        hesapDokumBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        hesapDokumBtn.setText("HESAP DÖKÜMÜ");
        hesapDokumBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hesapDokumBtnActionPerformed(evt);
            }
        });

        transferBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        transferBtn.setText("TRANSFER");
        transferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cıkısYapBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(transferBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hesapDokumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(yatırmaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bakiyeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(cekmeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sifreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yatırmaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bakiyeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cekmeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sifreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hesapDokumBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cıkısYapBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(welcomeLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yatırmaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yatırmaBtnActionPerformed
       cekmeGUI cek=new cekmeGUI();
       cek.setVisible(true);
       
        dispose();
    }//GEN-LAST:event_yatırmaBtnActionPerformed

    private void cekmeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekmeBtnActionPerformed
        yatırmaGUI yatır=new yatırmaGUI();
       yatır.setVisible(true);
       
        dispose();
    }//GEN-LAST:event_cekmeBtnActionPerformed

    private void hesapDokumBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hesapDokumBtnActionPerformed
       ActivitiesGUI ActGUI=new ActivitiesGUI();
       ActGUI.setVisible(true);
       dispose();
    }//GEN-LAST:event_hesapDokumBtnActionPerformed

    private void transferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferBtnActionPerformed
       transferGUI trGUI=new transferGUI();
       trGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_transferBtnActionPerformed

    private void bakiyeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bakiyeBtnActionPerformed
      bakiyeGUI bakiye=new bakiyeGUI();
       bakiye.setVisible(true);
       
        dispose();
    }//GEN-LAST:event_bakiyeBtnActionPerformed

    private void cıkısYapBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cıkısYapBtnActionPerformed
      BankProjectGUI bPGUI=new BankProjectGUI();
      bPGUI.setVisible(true);
      dispose();
    }//GEN-LAST:event_cıkısYapBtnActionPerformed

    private void sifreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sifreBtnActionPerformed
        sifreChangeGUI sDGUI=new sifreChangeGUI();
        sDGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_sifreBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstPageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FirstPageGUI frame= new FirstPageGUI();
                 frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bakiyeBtn;
    private javax.swing.JButton cekmeBtn;
    private javax.swing.JButton cıkısYapBtn;
    private javax.swing.JButton hesapDokumBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton sifreBtn;
    private javax.swing.JButton transferBtn;
    private javax.swing.JLabel welcomeLbl2;
    private javax.swing.JButton yatırmaBtn;
    // End of variables declaration//GEN-END:variables
DBConnection conn=new DBConnection();
Statement st=null;
ResultSet rs=null;
PreparedStatement pt=null;
}
