/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;
import java.sql.*;
import Helper.DBConnection;
import bankproject.Costumer;
import bankproject.User;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import static GUIs.BankProjectGUI.data;
/**
 *
 * @author TURBOX
 */
public class sifreChangeGUI extends javax.swing.JFrame {
//static Costumer u1=new Costumer();
    /**
     * Creates new form sifreChangeGUI
     */
    public sifreChangeGUI() {
        initComponents();
    }
      public boolean passChange(String yeniSifre,String tcno){
        boolean key=false;
       try {
            
            String query="UPDATE user SET sifre=? WHERE tcno=?";
            Connection con=conn.connDB();
          //  st=con.createStatement();
            pt=con.prepareStatement(query);
            pt.setString(1, yeniSifre);
            pt.setString(2, tcno);
            pt.executeUpdate();
            key=true;
        } catch (SQLException ex) {
            Logger.getLogger(Costumer.class.getName()).log(Level.SEVERE, null, ex);
        }
       if(key)
           return true;
       else 
           return false;
   } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        geriYatırBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        eskiSifLbl = new javax.swing.JLabel();
        yeniSifLbl = new javax.swing.JLabel();
        yeniSifTekLbl = new javax.swing.JLabel();
        eskiSifTxt = new javax.swing.JTextField();
        yeniSifTxt = new javax.swing.JTextField();
        yeniSifTekTxt = new javax.swing.JTextField();
        degistirBtn = new javax.swing.JButton();
        geriSifreBtn = new javax.swing.JButton();

        geriYatırBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        geriYatırBtn.setText("<<  GERİ");
        geriYatırBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriYatırBtnActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/kurtbank.png"))); // NOI18N

        eskiSifLbl.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        eskiSifLbl.setText("ESKİ ŞİFRE");

        yeniSifLbl.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        yeniSifLbl.setText("YENİ ŞİFRE");

        yeniSifTekLbl.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        yeniSifTekLbl.setText("YENİ ŞİFRE TEKRAR");

        eskiSifTxt.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N

        yeniSifTxt.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N

        yeniSifTekTxt.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N

        degistirBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        degistirBtn.setText("DEĞİŞTİR");
        degistirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                degistirBtnActionPerformed(evt);
            }
        });

        geriSifreBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        geriSifreBtn.setText("<<  GERİ");
        geriSifreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriSifreBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(eskiSifLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eskiSifTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(yeniSifLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yeniSifTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yeniSifTekLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(geriSifreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(degistirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yeniSifTekTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eskiSifLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eskiSifTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(yeniSifLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(yeniSifTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yeniSifTekLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yeniSifTekTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degistirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(geriSifreBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void degistirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_degistirBtnActionPerformed
        if(eskiSifTxt.getText().equals("")||yeniSifTxt.getText().equals("")||yeniSifTekTxt.getText().equals("")){
            JOptionPane.showMessageDialog(null,"LÜTFEN BOŞ KISIMLARI DOLDURUNUZ","DİKKAT",JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                Connection con=conn.connDB();
                st=con.createStatement();
                rs=st.executeQuery("SELECT*FROM user");
                while(rs.next()){
                    if(eskiSifTxt.getText().equals(data[3])){
                        if(yeniSifTxt.getText().equals(yeniSifTekTxt.getText())){
                            passChange(yeniSifTxt.getText(),(String) data[2]);
                            JOptionPane.showMessageDialog(null,"ŞİFRE BAŞARI İLE DEĞİŞTİRİLDİ","DİKKAT!",JOptionPane.WARNING_MESSAGE);
                            BankProjectGUI bPGUI=new BankProjectGUI();
                            bPGUI.setVisible(true);
                            dispose();
                           break;
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"YENİ ŞİFRE İLE YENİ ŞİFRE TEKRAR BİRBİRİNE EŞİT DEĞİL!","DİKKAT!",JOptionPane.WARNING_MESSAGE);
                            break;
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"ESKİ ŞİFRE YANLIŞ GİRİLDİ","DİKKAT!",JOptionPane.WARNING_MESSAGE);
                        break;
                    }
                }   } catch (SQLException ex) {
                Logger.getLogger(sifreChangeGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_degistirBtnActionPerformed

    private void geriYatırBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriYatırBtnActionPerformed
        FirstPageGUI fpGUI=new FirstPageGUI();
        fpGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_geriYatırBtnActionPerformed

    private void geriSifreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriSifreBtnActionPerformed
        FirstPageGUI fpGUI=new FirstPageGUI();
        fpGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_geriSifreBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sifreChangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sifreChangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sifreChangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sifreChangeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sifreChangeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton degistirBtn;
    private javax.swing.JLabel eskiSifLbl;
    private javax.swing.JTextField eskiSifTxt;
    private javax.swing.JButton geriSifreBtn;
    private javax.swing.JButton geriYatırBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel yeniSifLbl;
    private javax.swing.JLabel yeniSifTekLbl;
    private javax.swing.JTextField yeniSifTekTxt;
    private javax.swing.JTextField yeniSifTxt;
    // End of variables declaration//GEN-END:variables
DBConnection conn=new DBConnection();
Statement st=null;
ResultSet rs=null;
PreparedStatement pt=null;



}
