/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;


import Helper.DBConnection;
import bankproject.Activities;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.*;
import javax.swing.JOptionPane;
import static GUIs.BankProjectGUI.data;
/**
 *
 * @author Kerem
 */
public class transferGUI extends javax.swing.JFrame {
bakiyeGUI bGUI=new bakiyeGUI();
static Activities act=new Activities();
    /**
     * Creates new form transferGUI
     */
    public transferGUI() {
        initComponents();
        bGUI.runUpdate();
        showBakiye((String) data[2], (int) data[5]);
    }
 public void trYatan(int trYatan,int ebakiye,String iban){
       try {
           
           int yybakiye=0;
           
          
           yybakiye=ebakiye+trYatan;
           Connection con=conn.connDB();
           st=con.createStatement();
           pt=con.prepareStatement("UPDATE user SET bakiye=? WHERE iban=?");
           pt.setInt(1, yybakiye);
           pt.setString(2, iban);
           pt.executeUpdate();
       } catch (SQLException ex) {
           Logger.getLogger(FirstPageGUI.class.getName()).log(Level.SEVERE, null, ex);
       }
    }
  public boolean trCekilen(int trCekilen,int ebakiye,String iban){
                  int ybakiye=0;
                  boolean key=false;
           if(ebakiye>0&&ebakiye>=trCekilen){
          
      try {
             ybakiye=ebakiye-trCekilen;
           
           Connection con=conn.connDB();
           st=con.createStatement();
           pt=con.prepareStatement("UPDATE user SET bakiye=? WHERE iban=?");
           pt.setInt(1, ybakiye);
           pt.setString(2, iban);
           pt.executeUpdate();
           Helper.OptionPane.showMsg("success");
           key=true;
       } catch (SQLException ex) {
           Logger.getLogger(FirstPageGUI.class.getName()).log(Level.SEVERE, null, ex);
       }}
           else{
               JOptionPane.showMessageDialog(null,"BAKİYENİZ BU İŞLEM İÇİN YETERSİZDİR","İŞLEM BAŞARISIZ",JOptionPane.WARNING_MESSAGE);
           }
           if(key)
               return true;
           else
               return false;
    }
      public void transfer(String iban) throws SQLException{
       try {
           Connection con=conn.connDB();
           st=con.createStatement();
           rs=st.executeQuery("SELECT * FROM user WHERE iban="+iban);
           while(rs.next()){
               if(rs.getString("iban").equals(iban)){
                   if(!rs.getString("iban").equals(data[4])){
                boolean control=trCekilen(Integer.parseInt(trYatanTxt.getText()), (int) data[5], (String) data[4]);
                if(control==true){
                    trYatan(Integer.parseInt(trYatanTxt.getText()), Integer.parseInt(rs.getString("bakiye")), iban);
                    bGUI.runUpdate();
                    act.AddActivity((String)data[1], (String)data[2],Integer.parseInt(trYatanTxt.getText()),(int)data[5], "TRANSFER", (String)data[4]);
                   trIbanTxt.setText(null);
                  trYatanTxt.setText(null);
                  break;
                }
                else{
                    break;
                }
               }
                   else{
                        JOptionPane.showMessageDialog(null, "GİRİLEN IBAN,KULLANICI GİRİŞİ YAPILAN IBAN İLE AYNI","KAYIT BULUNAMADI",JOptionPane.WARNING_MESSAGE);
                   }
               }
               else{
                   JOptionPane.showMessageDialog(null, "GİRİLEN IBAN SİSTEMDE BULUNAMADI","KAYIT BULUNAMADI",JOptionPane.WARNING_MESSAGE);
                   break;
               }
                
           }
       } catch (SQLException ex) {
           Logger.getLogger(FirstPageGUI.class.getName()).log(Level.SEVERE, null, ex);
       }
      }
      
      
      
      
       private void showBakiye(String tcno,int bakiye){
         try {
                Connection con=conn.connDB();
            
                st=con.createStatement();
                rs=st.executeQuery("SELECT * FROM user  WHERE tcno="+tcno);
            while(rs.next()){
                trBakiyeLbl.setText("BANKAMIZDA BULUNAN MEVCUT BAKİYENİZ " +bakiye + "TL");
    }
            } catch (SQLException ex) {
                Logger.getLogger(bakiyeGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        trIbanLbl = new javax.swing.JLabel();
        trBakiyeLbl = new javax.swing.JLabel();
        trYatanLbl = new javax.swing.JLabel();
        trIbanTxt = new javax.swing.JTextField();
        trYatanTxt = new javax.swing.JTextField();
        trBtn = new javax.swing.JButton();
        geriYatırBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(620, 500));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/kurtbank.png"))); // NOI18N

        trIbanLbl.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        trIbanLbl.setText("TRANSFER YAPILACAK IBAN");

        trBakiyeLbl.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        trBakiyeLbl.setText("1");

        trYatanLbl.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        trYatanLbl.setText("TRANSFER YAPILACAK TUTAR");

        trIbanTxt.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N

        trYatanTxt.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N

        trBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        trBtn.setText("TRANSFER YAP");
        trBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trBtnActionPerformed(evt);
            }
        });

        geriYatırBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        geriYatırBtn.setText("<<  GERİ");
        geriYatırBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriYatırBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trIbanLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trYatanLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(trIbanTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(trYatanTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(trBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(trBakiyeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geriYatırBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(trBakiyeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trIbanLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trIbanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trYatanLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trYatanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geriYatırBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void geriYatırBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriYatırBtnActionPerformed
       FirstPageGUI fpGUI=new FirstPageGUI();
        fpGUI.setVisible(true);
        dispose();
    }//GEN-LAST:event_geriYatırBtnActionPerformed

    private void trBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trBtnActionPerformed
        if(trIbanTxt.getText().equals("")||trYatanTxt.getText().equals("")){
            Helper.OptionPane.showMsg("fill");
        }else{
            try {
                transfer(trIbanTxt.getText());
                
                bGUI.runUpdate();
                showBakiye((String) data[2], (int) data[5]);
            } catch (SQLException ex) {
                Logger.getLogger(transferGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
    }//GEN-LAST:event_trBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transferGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transferGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transferGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transferGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transferGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton geriYatırBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel trBakiyeLbl;
    private javax.swing.JButton trBtn;
    private javax.swing.JLabel trIbanLbl;
    private javax.swing.JTextField trIbanTxt;
    private javax.swing.JLabel trYatanLbl;
    private javax.swing.JTextField trYatanTxt;
    // End of variables declaration//GEN-END:variables
DBConnection conn=new DBConnection();
Connection con=conn.connDB();
Statement st=null;
ResultSet rs=null;
PreparedStatement pt=null;


}
