/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUIs;



import Helper.DBConnection;
import bankproject.BankProject;
import bankproject.Costumer;
import static GUIs.bakiyeGUI.*;

import bankproject.Activities;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import static GUIs.BankProjectGUI.data;

/**
 *
 * @author TURBOX
 */
public class yatırmaGUI extends javax.swing.JFrame {
static BankProject bP=new BankProject();
bakiyeGUI bGUI=new bakiyeGUI();
static ActivitiesGUI actGUI=new ActivitiesGUI();
static Activities act=new Activities();
 boolean key=false;
    /**
     * Creates new form yatırmaGUI
     */
    public yatırmaGUI() {
       
    try {
        initComponents();
        Connection con=conn.connDB();
        st=con.createStatement();
        rs=st.executeQuery("SELECT*FROM user");
        while(rs.next()){
            String bakiye=String.valueOf(data[5]);
            mevcutYatTxt.setText(bakiye);
        }
    } catch (SQLException ex) {
        Logger.getLogger(yatırmaGUI.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    public int yatma(int ebakiye,String tcno,int yatan){
         int ybakiye=0;
        try {
           
            ybakiye=ebakiye+yatan;
            
            Connection con=conn.connDB();
            String query="UPDATE user SET bakiye=? WHERE tcno=?";
            //st=con.createStatement();
            pt=con.prepareStatement(query);
            pt.setInt(1,ybakiye);
            pt.setString(2,tcno);
            pt.executeUpdate();
            JOptionPane.showMessageDialog(null,"Para Yatırma İşlemi Başarı İle Gerçkleşti","BAŞARILI",JOptionPane.WARNING_MESSAGE);
            key=true;
         
        } catch (SQLException ex) {
            Logger.getLogger(Costumer.class.getName()).log(Level.SEVERE, null, ex);
        }
           return ybakiye;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mevcutBakiyeLbl = new javax.swing.JLabel();
        cekilecekTutar = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        geriBtn = new javax.swing.JButton();
        cekBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        mevcutBakiyeLbl1 = new javax.swing.JLabel();
        yatırılacakTutarLbl = new javax.swing.JLabel();
        mevcutYatTxt = new javax.swing.JTextField();
        yatırılacakTxt = new javax.swing.JTextField();
        geriYatırBtn = new javax.swing.JButton();
        yatırBtn = new javax.swing.JButton();

        mevcutBakiyeLbl.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        mevcutBakiyeLbl.setText("Mevcut Bakiyeniz");

        cekilecekTutar.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        cekilecekTutar.setText("Cekilecek Tutar");

        jTextField2.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N

        jTextField1.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N

        geriBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        geriBtn.setText("GERİ");

        cekBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        cekBtn.setText("ÇEK");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(650, 500));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUIs/kurtbank.png"))); // NOI18N

        mevcutBakiyeLbl1.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        mevcutBakiyeLbl1.setText("Mevcut Bakiyeniz");

        yatırılacakTutarLbl.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        yatırılacakTutarLbl.setText("Yatırılacak Tutar");

        mevcutYatTxt.setEditable(false);
        mevcutYatTxt.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N

        yatırılacakTxt.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N

        geriYatırBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        geriYatırBtn.setText("<<  GERİ");
        geriYatırBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geriYatırBtnActionPerformed(evt);
            }
        });

        yatırBtn.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        yatırBtn.setText("YATIR");
        yatırBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yatırBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mevcutBakiyeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mevcutYatTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yatırılacakTutarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(geriYatırBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yatırBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(yatırılacakTxt)))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mevcutBakiyeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mevcutYatTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yatırılacakTutarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yatırılacakTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(yatırBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(geriYatırBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yatırBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yatırBtnActionPerformed
      if(yatırılacakTxt.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Lütfen Yatırılacak Tutarı Giriniz!!!","DİKKAT!",JOptionPane.WARNING_MESSAGE);
      }else{
          try{
          Connection con=conn.connDB();
          st=con.createStatement();
          rs=st.executeQuery("SELECT*FROM user ");
          while(rs.next()){
          yatma((int) data[5], (String) data[2],Integer.parseInt(yatırılacakTxt.getText()));
          bGUI.runUpdate();
           mevcutYatTxt.setText(String.valueOf(data[5]));
           // actGUI.setActData("YATAN");
        act.AddActivity((String)data[1], (String)data[2],Integer.parseInt(yatırılacakTxt.getText()),(int)data[5], "YATAN", (String)data[4]);
                  yatırılacakTxt.setText(null);
                  
                  FirstPageGUI fpGUI=new FirstPageGUI();
                  fpGUI.setVisible(true);
                  dispose();
                  break;
          }
          
          }catch (SQLException ex) {
                  Logger.getLogger(yatırmaGUI.class.getName()).log(Level.SEVERE, null, ex);
              }
            
      
        
         }   
      
    }//GEN-LAST:event_yatırBtnActionPerformed

    private void geriYatırBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geriYatırBtnActionPerformed
         FirstPageGUI fpGUI=new FirstPageGUI();
               fpGUI.setVisible(true);
               dispose();
    }//GEN-LAST:event_geriYatırBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yatırmaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yatırmaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yatırmaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yatırmaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yatırmaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cekBtn;
    private javax.swing.JLabel cekilecekTutar;
    private javax.swing.JButton geriBtn;
    private javax.swing.JButton geriYatırBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel mevcutBakiyeLbl;
    private javax.swing.JLabel mevcutBakiyeLbl1;
    private javax.swing.JTextField mevcutYatTxt;
    private javax.swing.JButton yatırBtn;
    private javax.swing.JLabel yatırılacakTutarLbl;
    private javax.swing.JTextField yatırılacakTxt;
    // End of variables declaration//GEN-END:variables
    
    
    DBConnection conn=new DBConnection();
    Connection con=conn.connDB();
    Statement st=null;
    ResultSet rs=null;
    PreparedStatement pt=null;
            


}
